### ISSUE TITLE
Update summary tags for `DatabaseInformation`.

### ISSUE THREAD

**Issue by tacosontitan** [tacosontitan/Density#1]
Currently, all of the `summary` tags are empty in the [`DatabaseInformation`](https://github.com/tacosontitan/Density/blob/main/Density/Sql/DatabaseInformation.cs) model. They should be updated to match the documentation for [`SqlConnectionStringBuilder`](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder?view=dotnet-plat-ext-6.0). For example, using the `UseIntegratedSecurity` property:

```csharp
<summary>
Gets or sets a `Boolean` value that indicates whether Username and Password are specified in the connection (when `false`) or whether the current Windows account credentials are used for authentication (when `true`).
</summary>
<returns>
The value of the IntegratedSecurity property, or false if none has been supplied.
</returns>
<remarks>
This property corresponds to the "Integrated Security" and "trusted_connection" keys within the connection string.
</remarks>
public bool UseIntegratedSecurity { get; set; }
```

**Comment by Mshehu5** [comment]
Can I take care of this?

**Comment by Mshehu5** [comment]
I have populated almost all the summary tags to match the  documentation for
 [ SqlConnectionStringBuilder](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder?view=dotnet-plat-ext-6.0) but I can't find the summary for the last two tags below can you help
```
namespace Density.Sql
{
     <summary>
    
    </summary>
    public class DatabaseInformation
    {
         <summary>
         
         </summary>
```

**Comment by tacosontitan** [comment]
> I have populated almost all the summary tags to match the documentation for [ SqlConnectionStringBuilder](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder?view=dotnet-plat-ext-6.0) but I can't find the summary for the last two tags below can you help...

Absolutely; the top level information for the `class` will be written by me, and the first property is `UseIntegratedSecurity` which is named `IntegratedSecurity` in `SqlConnectionStringBuilder` and given in the issue description.
